version: '3'
services:
  database:
    image: 'bitnami/mariadb'
    environment:
      - MARIADB_USER=moodleuser
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
  #  volumes:
  #    - '/var/dbdata:/bitnami'
  moodle:
    image: 'bitnami/moodle'
    environment:
      - MARIADB_HOST=database
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodleuser
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
 #   volumes:  
 #     - '/var/moodledata:/bitnami'
    ports:
      - "80:80"
      - "443:443" 
    links:
      - database  

